package googleplayservices.samples.android.treehouse.com.colourful2;

/**
 * Created by Nomore on 17/06/04.
 */

public class Schools {
    public static String[] names = new String[]{"St Columbus High","Bryden High School","Northview College","Dawood High", "Falcon School", "GreenHood High","Heritage High", "Peterhouse School"
            ,"Stanley High","Trinity High"};
    public static int[] resourceIds = new int[]{R.drawable.bolton, R.drawable.bryden, R.drawable.correspondance, R.drawable.dawood,
            R.drawable.falcon, R.drawable.greenwood, R.drawable.heritage, R.drawable.peterhouse, R.drawable.stanley,
            R.drawable.trinity};
    public static String[] aboutschool = new String[]{
            "It is based in Makokoba ,Bulwayo.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "Situated on 103km peg from Harare on the Harare-Bulawayo road, Chegutu Mashonaland West,Bryden High School is a non-denominational primary school.`A VIEW OF THE SCHOOL  It is a single stream primary school with an average 12 boys and 12 girls in a class.The total enrollment stands atan average of  157.  A high staff-pupil ratio ensures each pupil receives the interest and attention they need in the classroom and on the sports field.Classes from Grade 0-7." +
                    "`SPORTS and CLUBS\n Hockey\n" +
                    "Swmming\n" +
                    "Chess Club\n" +
                    "Athletics\n" +
                    "Tennis\n" +
                    "Cross country\n" +
                    "Cricket\n" +
                    "Christmas Craft Club\n" +
                    "Duathlon\n" +
                    "Dance\n" +
                    "Young Farmers’\n" +
                    "French\n" +
                    "Cookery\n" +
                    "Conservation\n" +
                    "Computers.`FEES STRUCTURE" + "\n" +
                    "    US$1,960.00 (day)\n" +
                    "    US$2,950.00 (weekly boarding)\n" +
                    "    US$3,450.00 (boarding)\n" +
                    "\n",
            "It is based in Makokoba ,Bulwayo.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "Falcon College is a boys’ boarding school in Esigodini, Zimbabwe – situated 60km from Bulawayo on the Beit Bridge road.ties enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "Falcon College is a boys’ boarding school in Esigodini, Zimbabwe – situated 60km from Bulawayo on the Beit Bridge road. There is a strong Christian ethos based on the good, old-fashioned values of impeccable manners, pride in one’s dress and a neat and tidy personal living space. There is an inherent respect for our elders and those in positions of authority.`A VIEW OF THE SCHOOL  Our extravagant class sizes of never more than 30 students down to some classes as small as 3 students, enable individual attention for those with special needs without “labelling” them in any way.Falcon offers the Cambridge examinations at Checkpoint, IGCSE, AS and A level. We also offer some HEXCO and City and Guilds subjects.The school is dynamically embarking on modern teaching and coaching techniques, with electronic media being used in every classroom equipped with Wi-Fi.`FEES STRUCTURE \n" +
                    "    Processing and Registration Fee – US$ 50.00\n" + "    Acceptance of Place Fee (a non-refundable fee used for the development of the College) – US$2,500.00\n" +
                    "    Termly Boarding and Tuition Fees (there are three terms in the year)\n" +        "    2015 Fees Breakdown – per term (there are three terms per year)\n" +
                    "    Boarding and tuition – $4,100\n" + "    Accident insurance – $10\n" + "    Medical levy – $30\n" + "    Disbursement deposit – $300\n" + "    Remission insurance –  $30\n",
            "It is based in Gweru.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "It is based in Victoria Falls ,Bulwayo.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "It is based in Beitbridge.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "It is based in Harare.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",
            "It is based in Mutare.It offers a good all round ,child centred education with a strong technical bias in a Anglican Christian environment in addition to a wide of academic and technical sujects being taught the school offers a variety of sporting and cultural activities enabling children to expand their horizons thereby developing in body ,mind and soul.`A VIEW OF THE SCHOOL  There are approximately 750 students,a maximum of 31 in each of the 4 classes at each form in Olevel.Advanced level students have 4 base classes.Subjects offered are as follows:   `ORDINARY LEVEL english ,intergrated science ,ndebele,history,english literature,commerce,accounts,fashion and fabrics,geography,religous studies,biology,technical graphics ,food and nutrition,woowork,commercial studies(typing),computers and metal work.There are 2 kitchens for food and nutrition one of with mini-kitchens and a lab for the rest of the practicals.  `ADVANCED LEVEL  english ,ndebele,mathematics,physics,geography,accounting,divinity,chemestry,foodscience,management of business,geometrical&mech.draw,history and biology.`FEES STRUCTURE  The current fees for ordinary and advanced level is 250 ,310 respectively .This is payable in 3 instalments and includes free excersise books for students as per need as well as travel costs n some provisions for any school acivities such as competitions.",};
    public static String[] detail = new String[]{
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 87,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are a looking for is school with high staff-pupil ratio that ensures each pupil receives the interest and attention they need in the classroom and other co curriculum activities then Bydren is the one.It is no coincidence that our children are consistently found amongst the top achievers in sporting, music and academic representatives.\nSchool starts at 7:45am on Mondays and ends at 12:30pm on Fridays unless the children are involved in sporting fixtures. \n /NB/There are currently places for ECD level ONLY",
            "WHY YOU SHOULD CONSIDER US`If you want the best for your children in terms of quality academic and sporting activities.Its passrate last year was sitting at 87,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 90,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 97,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 86% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 76,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 89,7% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 92,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level",
            "WHY YOU SHOULD CONSIDER US`If what you are looking for is a school with strong religous values,good principles,security,safe infustruture,a healthy learning environment and most importantly a school that excels in accademics as well as sports and culture then St columbas is the school you looking for.St columba's is well known for its good pass rate in both ordinary and alevel .Its passrate last year was sitting at 94,6% at olevel and 73,2 at advanced level .Students attend mass every Wenesday ,only the main gate with a guard on duty is open during schools hours,there are stuff members who keep the school clean each day . /NB/There are currently 9 places for ordinary level and 5 at advanced level"};
    public static String[] pop = new String[]{"Way to go, %1$s"};
}
